import classes from "./SectionWhy.module.css";
import health from "../images/health4.png";
import environment from "../images/environment4.png";
import animals from "../images/animals2.png";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowCircleUp } from "@fortawesome/free-solid-svg-icons";

const SectionWhy = () => {

  const scrollHandler = () => {
    window.scrollTo({
      top: -900,
      behavior: "smooth"
    })
  }

  return (
    <>
      <section className={classes.why} id="why">
        <h2 className={classes.secondary}>Why go vegetarian?</h2>
        <div className={classes.container}>
          <div className={classes.text}>
            <h3 className={classes.tertiary}>Because it is healthy</h3>
            <p className={classes.description}>
              Vegetarian diets tend to be naturally lower in saturated fat and
              cholesterol and have a higher intake of plant nutrients than most
              meat-based diets. Vegetarians have been shown to have a 24% lower
              risk of dying of heart disease than non-vegetarians. Furthermore,
              world-renowned physician Dr. Dean Ornish found that patients on a
              low-fat vegetarian diet actually reversed coronary heart disease.
            </p>
          </div>
          <div className={classes.imgBox}>
            <img src={health} className={classes.image} alt='health'></img>
          </div>

          <div className={classes.imgBox}>
            <img src={environment} className={classes.image} alt='environment'></img>
          </div>
          <div className={classes.text}>
            <h3 className={classes.tertiary}>
              Because it is good for the environment
            </h3>
            <p className={classes.description}>
              The United Nations said in its 2006 report that livestock generate
              more greenhouse gases than all the cars and trucks in the world
              combined. Most of it comes from carbon dioxide and nitrous oxide
              gases generated by manure. Therefore, the single most important
              step an individual can take to reduce global warming is to adopt a
              vegetarian diet.
            </p>
          </div>

          <div className={classes.text}>
            <h3 className={classes.tertiary}>
              Because animals are our friends
            </h3>
            <p className={classes.description}>
              Animals on today's factory farms have no legal protection from
              cruelty that would be illegal if it were inflicted on dogs or
              cats. Yet farmed animals are no less intelligent or capable of
              feeling pain than are the dogs and cats we cherish as companions.
              A vegetarian lifestyle awakens our spirit of compassion and guides
              us towards a kinder, gentler society in which we exercise a moral
              choice to protect animals—not exploit them
            </p>
          </div>
          <div className={classes.imgBox}>
            <img src={animals} className={classes.image} alt='animals'></img>
          </div>
        </div>
          <button className={classes.btn} onClick={scrollHandler}>
            <FontAwesomeIcon icon={faArrowCircleUp} className={classes.icon}></FontAwesomeIcon>
          </button>
      </section>
    </>
  );
};

export default SectionWhy;
